apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
  labels:
    app.kubernetes.io/name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout
    spec:
      containers:
      - name: checkoutimage
        image: keelymac32/checkoutimage
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "200Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: checkout
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31001