apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
  labels:
    app.kubernetes.io/name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout
    spec:
      containers:
      - name: checkout-image
        image: keelymac32/checkoutimage
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: checkout
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8080