apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
  labels:
    app.kubernetes.io/name: checkout
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout
    spec:
      containers:
      - name: checkout-image
        image: keelymac32/checkout
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: checkout
